version: "{branch} #{build}"

shallow_clone: true

image:
    - Visual Studio 2017

platform:
    - Win32
    - x64

configuration:
    - Debug
    - Release

environment:
    matrix:
        - generator: "Visual Studio 15 2017"

matrix:
    fast_finish: true

before_build:
    - mkdir build && cd build
    - cmake -A %platform% -G "%generator%" ..

build_script:
    - cmake --build . --config %configuration%

test_script:
- ctest --output-on-failure -C %configuration%
